name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.1.0
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  csv: ^6.0.0
  #backendless_sdk: ^7.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    #- assets/data/Bus1.webp
    #- assets/data/bus2.webp
    #- assets/data/bus3.webp
    - assets/data/bus_routes.csv
